import { WindowTypes, PriorityLevels } from './windowTypes';

export const initialWindows = [
  { id: '1', content: 'Обновление', type: WindowTypes.SYSTEM, priority: PriorityLevels.HIGH, line: 1, description: 'Блокирующий попап необходимости обновить приложение' },
  { id: '2', content: 'Покупки', type: WindowTypes.SYSTEM, priority: PriorityLevels.HIGH, line: 1, description: 'Обработка и начисление отложенных покупок' },
  { id: '3', content: 'Win Streak Loose', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Отображение потери стрика' },
  { id: '4', content: 'Island Fail', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'При проигрыше в ивенте' },
  { id: '5', content: 'Анлок фичи', type: WindowTypes.SYSTEM, priority: PriorityLevels.MEDIUM, line: 2, description: 'Отображение анлока фичи (улетание шариков с иконки)' },
  { id: '6', content: 'New Booster', type: WindowTypes.TUTORIAL, priority: PriorityLevels.MEDIUM, line: 2, description: 'New Booster Open - перед уровнем с туториалом бустеров' },
  { id: '7', content: 'Нотификации', type: WindowTypes.SYSTEM, priority: PriorityLevels.LOW, line: 3, description: 'Попап запроса разрешения на показ нотификаций (iOS only)' },
  { id: '8', content: 'Челлендж', type: WindowTypes.PROGRESS, priority: PriorityLevels.MEDIUM, line: 2, description: 'Отображение изменения прогресса по челленджу' },
  { id: '9', content: 'Прогресс', type: WindowTypes.PROGRESS, priority: PriorityLevels.MEDIUM, line: 2, description: 'Отображение других изменений прогресса после завершения уровня' },
  { id: '10', content: 'Сундук уровней', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Открытие сундука уровней если он заполнился' },
  { id: '11', content: 'Сундук звёзд', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Открытие сундука звёзд если он заполнился' },
  { id: '12', content: 'Промокоды', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Начисление награды за промокоды' },
  { id: '13', content: 'New Pack', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'New Pack Open - каждый холидей, 1 раз, при старте холидея' },
  { id: '14', content: 'Win Streak', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Win Streak Reward - получение награды' },
  { id: '15', content: 'Island Progress', type: WindowTypes.PROGRESS, priority: PriorityLevels.MEDIUM, line: 2, description: 'Island Progress - при каждом успешном выходе из уровня' },
  { id: '16', content: 'Collect Items', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Collect Items Event Reward - при доступности получения награды' },
  { id: '17', content: 'Star Tournament', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Star Tournament Reward - при доступности получения награды' },
  { id: '18', content: 'Boss Challenge', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Boss Challenge Reward - при доступности получения награды' },
  { id: '19', content: 'Гонка', type: WindowTypes.PROGRESS, priority: PriorityLevels.MEDIUM, line: 2, description: 'Прогресс гонки - если завершён этап, в котором пользователь принимал участие' },
  { id: '20', content: 'Харвест', type: WindowTypes.PROGRESS, priority: PriorityLevels.MEDIUM, line: 2, description: 'Окно прогресса харвест ивента - если ивент завершён и пользователь принимал в нём участие' },
  { id: '21', content: 'Piggy Bank', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Piggy Bank - при первом анлоке' },
  { id: '22', content: 'Collect Start', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Collect Items Event Start - однократно при старте нового ивента сбора предметов' },
  { id: '23', content: 'Star Tournament', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Star Tournament - однократно когда новый эвент доступен для старта' },
  { id: '24', content: 'Island Start', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Island Start - при старте ивента' },
  { id: '25', content: 'Honey Factory', type: WindowTypes.EVENT, priority: PriorityLevels.LOW, line: 3, description: 'Honey Factory - Annonce - В состоянии анонса, один раз в день' },
  { id: '26', content: 'Honey Factory', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Honey Factory - Start - В состоянии возможности старта, один раз за эвент' },
  { id: '27', content: 'Win Streak', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Win Streak Start - однократно в случае если запустился новый ивент вин стрик' },
  { id: '28', content: 'Челлендж оффер', type: WindowTypes.OFFER, priority: PriorityLevels.LOW, line: 3, description: 'Челлендж оффер - периодически, период конфигурируется' },
  { id: '29', content: 'Бест-старт', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Бест-старт оффер - один раз после каждого холодного старта' },
  { id: '30', content: 'Бест-старт N уровней', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Бест-старт оффер - один раз каждые N уровней' },
  { id: '31', content: 'Но-адс оффер', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Но-адс оффер - при активации оффера и после просмотра каждых N реклам' },
  { id: '32', content: 'Чейн оффер', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Чейн оффер - один раз после каждого холодного старта' },
  { id: '33', content: 'Чуз ван оффер', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Чуз ван оффер - один раз после каждого холодного старта' },
  { id: '34', content: 'Battle Pass Reward', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Battle Pass Reward - при завершении времени БП, выдача собранной награды' },
  { id: '35', content: 'Battle Pass Buy', type: WindowTypes.SYSTEM, priority: PriorityLevels.HIGH, line: 1, description: 'Battle Pass Buy - если был куплен в кор геймплее' },
  { id: '36', content: 'Level Calendar', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Level Calendar - наступил новый день' },
  { id: '37', content: 'Мотивация логина', type: WindowTypes.SYSTEM, priority: PriorityLevels.LOW, line: 3, description: 'Показ попапа мотивации логина' },
  { id: '38', content: 'Lucky Factory Start', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Lucky Factory - при старте ивента' },
  { id: '39', content: 'Lucky Factory End', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Lucky Factory - при окончании ивента' },
  { id: '40', content: 'Lucky Factory Progress', type: WindowTypes.PROGRESS, priority: PriorityLevels.MEDIUM, line: 2, description: 'Lucky Factory - При выходе с уровня, если билетов ивента >= необходимого для броска кубика количества' },
  { id: '41', content: 'Battle Pass Offer', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Battle Pass Offer - раз в день, если БП не куплен' },
  { id: '42', content: 'Прогрессив оффер', type: WindowTypes.PROGRESS, priority: PriorityLevels.MEDIUM, line: 2, description: 'Показ достижения чекпоинта в прогрессив оффере' },
  { id: '43', content: 'Прогрессив оффер награда', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Показ завершённого купленного прогрессив оффера при наличии несобранных наград' },
  { id: '44', content: 'Новый прогрессив оффер', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Показ доступности нового прогрессив оффера' },
  { id: '45', content: 'Дейли бонус', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Дейли бонус - если зарядился' },
  { id: '46', content: 'Новый челлендж', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Челлендж - если стартовал новый челендж' },
  { id: '47', content: 'Туториал команды', type: WindowTypes.TUTORIAL, priority: PriorityLevels.MEDIUM, line: 2, description: 'Туториал о присоединении к команде - по достижении уровня когда открываются команды' },
  { id: '48', content: 'Анонс гонки', type: WindowTypes.EVENT, priority: PriorityLevels.LOW, line: 3, description: 'Попап анонса/возможности старта гонки - один раз в календарный день' },
  { id: '49', content: 'Старт харвеста', type: WindowTypes.EVENT, priority: PriorityLevels.MEDIUM, line: 2, description: 'Окно возможности старта харвест ивента - один раз в календарный день' },
  { id: '50', content: 'Туториал дейли челленджа', type: WindowTypes.TUTORIAL, priority: PriorityLevels.MEDIUM, line: 2, description: 'Туториал дейли челленджа - один раз при активации дейли челленджа' },
  // Плейсмент "LevelExit"
  { id: '51', content: 'Победа с звездами', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Попап победы с звездами при выполнении целей уровня' },
  { id: '52', content: 'Start Chest', type: WindowTypes.REWARD, priority: PriorityLevels.HIGH, line: 1, description: 'Окно награды "Start Chest" при условии сбора сундука' },
  { id: '53', content: 'Rate Us', type: WindowTypes.SYSTEM, priority: PriorityLevels.MEDIUM, line: 2, description: 'Попап Rate Us - при выигрыше на уровне не ниже указанного в конфиге' },
  { id: '54', content: 'Докупка очистки', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Попап докупки очистки панели, если закончилось место на панели сбора' },
  { id: '55', content: 'Докупка времени', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Попап докупки времени, если закончилось время уровня' },
  { id: '56', content: 'Потеря элементов', type: WindowTypes.SYSTEM, priority: PriorityLevels.MEDIUM, line: 2, description: 'Попап потери собранных элементов на уровне (звезды, элементы ивентов)' },
  { id: '57', content: 'Потеря CrownRush', type: WindowTypes.SYSTEM, priority: PriorityLevels.MEDIUM, line: 2, description: 'Попап потери прогресс и бонусов CrownRush' },
  { id: '58', content: 'Переигать с бустером', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Попап предложения переиграть уровень с использованием бустера' },
  { id: '59', content: 'Оффер "кофе"', type: WindowTypes.OFFER, priority: PriorityLevels.MEDIUM, line: 2, description: 'Оффер отключения рекламы Interstitial "кофе"' },
  { id: '60', content: 'Interstitial', type: WindowTypes.SYSTEM, priority: PriorityLevels.LOW, line: 3, description: 'Реклама Interstitial' },
]; 